name: build

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Disk Cleanup
        run: .\disk_cleanup.bat
      - name: Build
        run: .\build.windows.bat
      - name: Upload artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-win-x64.tar
          path: package/libwebrtc-win-x64.tar
      - name: Upload artifact x86
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-win-x86.tar
          path: package/libwebrtc-win-x86.tar

  release:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win-x64
          - win-x86
        include:
          - name: win-x64
            ext: tar
            type: application/x-tar
          - name: win-x86
            ext: tar
            type: application/x-tar
    name: Release ${{ matrix.name }}
    needs:
     - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{ matrix.name }}
        uses: actions/download-artifact@v2
        with:
          name: libwebrtc-${{ matrix.name }}.${{ matrix.ext }}
      - name: Upload ${{ matrix.name }} Release asset
        uses: ncipollo/release-action@v1
        with:
          name: Release m${{ github.ref }}
          allowUpdates: true
          draft: false
          prerelease: false
          artifactContentType: ${{ matrix.type }}
          artifacts: libwebrtc-${{ matrix.name }}.${{ matrix.ext }}
          token: ${{ secrets.GITHUB_TOKEN }}
