name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - linux-x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Disk Cleanup
        run: ./disk_cleanup.sh
      - name: Build
        run: make -C docker USE_X11=1 ${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos-arm64
          - macos-x64
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make -C build USE_CCACHE=0 ${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Disk Cleanup
        run: .\disk_cleanup.bat
      - name: Build
        run: .\build.windows.bat
      - name: Upload artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-win-x64.tar.gz
          path: package/libwebrtc-win-x64.tar.gz
      - name: Upload artifact x86
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-win-x86.tar.gz
          path: package/libwebrtc-win-x86.tar.gz

  release:
    strategy:
      fail-fast: false
      matrix:
        name:
          - linux-arm64
          - linux-x64
          - macos-arm64
          - macos-x64
          - win-x64
        include:
          - name: linux-arm64
            ext: tar.xz
            type: application/x-xz
          - name: linux-x64
            ext: tar.xz
            type: application/x-xz
          - name: macos-arm64
            ext: tar.xz
            type: application/x-xz
          - name: macos-x64
            ext: tar.xz
            type: application/x-xz
          - name: win-x64
            ext: tar.gz
            type: application/gzip
    name: Release ${{ matrix.name }}
    if: contains(github.ref, 'tags/')
    needs:
     - build-linux
     - build-macos
     - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{ matrix.name }}
        uses: actions/download-artifact@v2
        with:
          name: libwebrtc-${{ matrix.name }}.${{ matrix.ext }}
      - name: Upload ${{ matrix.name }} Release asset
        uses: ncipollo/release-action@v1
        with:
          name: Release m${{ github.ref }}
          allowUpdates: true
          draft: false
          prerelease: false
          artifactContentType: ${{ matrix.type }}
          artifacts: libwebrtc-${{ matrix.name }}.${{ matrix.ext }}
          token: ${{ secrets.GITHUB_TOKEN }}
