name: Check new version

on:
  schedule:
    - cron: "30 5 * * 1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Patch ./VERSION
        id: patch_ver
        run: ./upgrade-ver.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_INSTRUMENTISTO_BOT_PAT }}
          commit-message: Upgrade to ${{ steps.patch_ver.outputs.version }} version
          branch: upgrade-to-${{ steps.patch_ver.outputs.version }}
          title: Upgrade to ${{ steps.patch_ver.outputs.version }}
          body: Upgrade libwebrtc version to ${{ steps.patch_ver.outputs.version }}.
          labels: k::version
          delete-branch: true
