name: Check new version

on:
  schedule:
    - cron: "30 5 * * 1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./upgrade-ver.sh
        id: patch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Upgrade to ${{ steps.patch.outputs.version }} version
          branch: upgrade-to-${{ steps.patch.outputs.version }}
          delete-branch: true
          title: Upgrade to ${{ steps.patch.outputs.version }}
          body: Upgrade `libwebrtc` version to ${{ steps.patch.outputs.version }}.
          labels: |
            enhancement
            k::version
          token: ${{ secrets.GH_INSTRUMENTISTO_BOT_PAT }}
